from typing import Any, Dict, Optional
from google.cloud.firestore import Client

class FirestoreCacheHandler:
    def __init__(self, collection_name: str = 'python-exact-online-cache') -> None: ...
    def resetCache(self) -> Dict[str, Any]: ...
    def getCache(self, key: str) -> Optional[Dict[str, Any]]: ...
    def setCache(self, key: str, value: Dict[str, Any]) -> None: ...
    def deleteCache(self, key: str) -> None: ...