from typing import Any, Dict, Optional

class CacheHandler:
    def __init__(self) -> None: ...
    def resetCache(self) -> Dict[str, Any]: ...
    def getCache(self, key: str) -> Optional[Any]: ...
    def setCache(self, key: str, value: Any) -> str: ...
    def deleteCache(self, key: str) -> None: ...